//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacDichVuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CacDichVuKham()
        {
            this.PhieuThuChiTiets = new HashSet<PhieuThuChiTiet>();
        }
    
        public int ID { get; set; }
        public string TenDV { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<bool> Chon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThuChiTiet> PhieuThuChiTiets { get; set; }
    }
}
