//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTuXuatBan
    {
        public int ID { get; set; }
        public string MaHS { get; set; }
        public Nullable<short> LanKham { get; set; }
        public string SoChungTu { get; set; }
    }
}
