//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTuNhapXuat2
    {
        public int IDChungTu { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> NgayCT { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<bool> CTNhap { get; set; }
        public Nullable<short> MaNV { get; set; }
        public string MaHS { get; set; }
    }
}
