//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMThuocDonGia2
    {
        public decimal IdGia { get; set; }
        public string MaThuoc { get; set; }
        public string SoLoThuoc { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string IDDonVi { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<short> Vat { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> NhaCungCap { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<int> TonDau { get; set; }
    }
}
