//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViSuDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViSuDung()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int IDDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string TenPM { get; set; }
        public string DiaChiPM { get; set; }
        public string DienThoaiPM { get; set; }
        public string FaxPM { get; set; }
        public string EmailPM { get; set; }
        public string MaSoThuePM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
