//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSThuoc
    {
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string HoatChat { get; set; }
        public Nullable<int> LoaiThuoc { get; set; }
        public string DonVi { get; set; }
        public Nullable<short> SoLuongTon { get; set; }
        public string MaHangSanXuat { get; set; }
        public string MaQuocGia { get; set; }
        public string GhiChu { get; set; }
    }
}
