//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int IDHoaDon { get; set; }
        public int MaChiTietPK { get; set; }
        public string MaHS { get; set; }
        public Nullable<short> LanKham { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public Nullable<short> MaNV { get; set; }
        public Nullable<decimal> ChiPhiKham { get; set; }
        public Nullable<decimal> ChiPhiThuoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuKham PhieuKham { get; set; }
    }
}
