//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBanThuoc
    {
        public int ID { get; set; }
        public string MaThuoc { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public string DonVi { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public string SoLo { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<short> MaNV { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string SoChungTu { get; set; }
        public string MaHS { get; set; }
    }
}
