//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoBN
    {
        public string MaHS { get; set; }
        public string HoTen { get; set; }
        public string Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GhiChu { get; set; }
        public string NgheNghiep { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string TSBenh { get; set; }
        public byte[] Hinh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string Thang { get; set; }
        public Nullable<int> MaQuanHuyen { get; set; }
        public string TagID { get; set; }
    }
}
