//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienQuyen
    {
        public short MaNV { get; set; }
        public string Quyen { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
