//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKhoThuoc
    {
        public int IDNhap { get; set; }
        public string MaThuoc { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public string IDDonVi { get; set; }
        public int NhaCungCap { get; set; }
        public Nullable<bool> KetQua { get; set; }
    
        public virtual NhaCungCap NhaCungCap1 { get; set; }
    }
}
