//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuChiTiet
    {
        public int ID { get; set; }
        public string MaHS { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<short> MaNV { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<int> LanKham { get; set; }
    
        public virtual CacDichVuKham CacDichVuKham { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
