//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTDHangNgay
    {
        public string MaHS { get; set; }
        public System.DateTime NgayTD { get; set; }
        public string MaNV { get; set; }
        public string NDdieuTri { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public string GhiChu { get; set; }
    }
}
