//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mrtademoEntities : DbContext
    {
        public mrtademoEntities()
            : base("name=mrtademoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CacDichVuKham> CacDichVuKhams { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChungTuNhapXuat2> ChungTuNhapXuat2 { get; set; }
        public virtual DbSet<DMThuocDonGia2> DMThuocDonGia2 { get; set; }
        public virtual DbSet<DonThuoc> DonThuocs { get; set; }
        public virtual DbSet<DonThuocMau> DonThuocMaus { get; set; }
        public virtual DbSet<DonThuocMauChiTiet> DonThuocMauChiTiets { get; set; }
        public virtual DbSet<DonViSuDung> DonViSuDungs { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<DSThuoc2> DSThuoc2 { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoSoBN> HoSoBNs { get; set; }
        public virtual DbSet<KetQuaCDHAnh> KetQuaCDHAnhs { get; set; }
        public virtual DbSet<LoaiThuoc> LoaiThuocs { get; set; }
        public virtual DbSet<LuuVet> LuuVets { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhapKhoThuoc> NhapKhoThuocs { get; set; }
        public virtual DbSet<PhieuHen> PhieuHens { get; set; }
        public virtual DbSet<PhieuKham> PhieuKhams { get; set; }
        public virtual DbSet<PTDHangNgay> PTDHangNgays { get; set; }
        public virtual DbSet<TreeChucNang> TreeChucNangs { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<ChungTuNhapXuat> ChungTuNhapXuats { get; set; }
        public virtual DbSet<ChungTuXuatBan> ChungTuXuatBans { get; set; }
        public virtual DbSet<DMKhoThuoc> DMKhoThuocs { get; set; }
        public virtual DbSet<DMKhoThuoc2> DMKhoThuoc2 { get; set; }
        public virtual DbSet<DMThuocDonGia> DMThuocDonGias { get; set; }
        public virtual DbSet<DSThuoc> DSThuocs { get; set; }
        public virtual DbSet<HoaDonBanThuoc> HoaDonBanThuocs { get; set; }
        public virtual DbSet<LieuDung> LieuDungs { get; set; }
        public virtual DbSet<NhanVienQuyen> NhanVienQuyens { get; set; }
        public virtual DbSet<PhieuThu> PhieuThus { get; set; }
        public virtual DbSet<PhieuThuChiTiet> PhieuThuChiTiets { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<QuocGia> QuocGias { get; set; }
        public virtual DbSet<tb_CanLamSang> tb_CanLamSang { get; set; }
        public virtual DbSet<tb_ChanDoan> tb_ChanDoan { get; set; }
        public virtual DbSet<tb_ChiDinh> tb_ChiDinh { get; set; }
        public virtual DbSet<tb_HangSanXuat> tb_HangSanXuat { get; set; }
        public virtual DbSet<tb_NhaCungCap> tb_NhaCungCap { get; set; }
        public virtual DbSet<tb_QuanHuyen> tb_QuanHuyen { get; set; }
        public virtual DbSet<tb_ThanhPho> tb_ThanhPho { get; set; }
        public virtual DbSet<tb_TrieuChung> tb_TrieuChung { get; set; }
        public virtual DbSet<YeuCauHT> YeuCauHTs { get; set; }
    }
}
