//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiDinh
    {
        public int MaChiDinh { get; set; }
        public string TenChiDinh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string GhiChu { get; set; }
    }
}
