//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhaCungCap
    {
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string DiaChiNhaCungCap { get; set; }
        public string DienThoaiNhaCungCap { get; set; }
        public string FaxNhaCungCap { get; set; }
        public string MaSoThue { get; set; }
        public string NguoiLienHe { get; set; }
        public string GhiChu { get; set; }
        public string MaQuanHuyen { get; set; }
    }
}
