//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeChucNang
    {
        public int ParentID { get; set; }
        public string ChucNang { get; set; }
        public Nullable<bool> Xem { get; set; }
        public Nullable<bool> Them { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> Sua { get; set; }
        public Nullable<bool> In { get; set; }
        public Nullable<short> MaNV { get; set; }
    }
}
