//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanLyPhongMach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauHT
    {
        public int ID { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string Ten { get; set; }
        public string YeuCau { get; set; }
        public string TeamView { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> DaHT { get; set; }
    }
}
